### PR TITLE
Various changes uploaded

### PR DESCRIPTION
**Pull request by MdHamid06**

### CODE REVIEW

**Comment by MohitNamdev22** [comment]
Hey @MdHamid06 why you closed the Repo and what changes have you made?

**Comment by MdHamid06** [comment]
> Hey @MdHamid06 why you closed the Repo and what changes have you made?

I have changed several color combination, changed the shape of the buttons and inserted pi button.
And I don't how my repo has been closed..how can i reopen it?

**Comment by MdHamid06** [comment]
I guess I have made to many change....should I work over it again?

**Comment by MohitNamdev22** [comment]
Actually your changes not reflected, i guess you haven't pushed your changes

**Comment by MdHamid06** [comment]
ohh okay ley me try once again!

**Comment by MdHamid06** [comment]
should i directly make changes in this online github editor?

**Pull request closed without merging**
